/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "VIS"
include(
    ":java:HelloWorld",
    ":socket:cpp:Hello",
    ":java:Hello",
    ":socket:cpp:Primitive_SocketServer",
    ":socket:cpp:Primitive_SocketClient",
    ":socket:cpp:Echo_SocketServer",
    ":socket:cpp:Udp_SocketServer",
    ":socket:cpp:Udp_SocketClient",
    ":socket:cpp:Ipv6_SocketServer",
    ":socket:cpp:Ipv6_SocketClient",
    ":socket:cpp:Environment_SocketServer",
    ":socket:java:Echo_SocketServer",
    ":socket:java:Echo_SocketClient",
    ":socket:java:Environment_SocketClient",
    ":general:EnvironmentI",
    ":rmi:Hello_RmiClient",
    ":rmi:Hello_RmiServer",
    ":rmi:Hello_RmiInterface"
    )
